### ISSUE TITLE
feat: Seed manifest data to local git repository.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-kubernetes-datavis#8]
**acceptance criteria:**
- we can initialize an empty local git repository
- we can seed commits for application releases
- the commits contain release number, commit, author, date, message, and a kubernetes `manifests.yaml` for each environment
- the application name is prefixed with its namespace

**task breakdown:**
- [x] `sources/model.ts`, write typescript types (via zod schemas) for `Environment`, `Application`, `Release`, `Deployment`
- [x] `sources/faker.ts`, write faker functions for kubernetes `manifests.yaml` and the other commit data from acceptance criteria
- [x] `sources/run/manifests-git.ts`, write git commits using model types and faker functions
- [ ] `sources/run/manifests-git.ts`, read git commit history into model types

**technical details:**
- should be similar to this custom directory schema:
```
applications/<application-name>/
├─ application-namespace.json
├─ releases/<release-number>/
│  ├─ release-author.json
│  ├─ release-commit.json
│  ├─ release-date.json
│  ├─ release-message.json
│  ├─ environments/development/
│  │  └─ manifests.yaml
│  ├─ environments/staging/
│  └─ environments/production/
environments/
├─ development/
│  └─ applications/<application-name>/
│     └─ release-number.json
├─ staging/
└─ production/
```
